CREATE SEQUENCE SEQ_LOCAL START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TRANSPORTADOR START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RESIDUO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_COLETA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DESTINO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ALERTA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1;