INSERT INTO LOCAL VALUES (SEQ_LOCAL.NEXTVAL, 'Fábrica Central', 'Av. das Indústrias, 1000');
INSERT INTO LOCAL VALUES (SEQ_LOCAL.NEXTVAL, 'Armazém Norte', 'Rua do Porto, 230');
INSERT INTO LOCAL VALUES (SEQ_LOCAL.NEXTVAL, 'Escritório Administrativo', 'Av. Paulista, 1500');
INSERT INTO LOCAL VALUES (SEQ_LOCAL.NEXTVAL, 'Posto de Coleta Sul', 'Rua Verde, 400');
INSERT INTO LOCAL VALUES (SEQ_LOCAL.NEXTVAL, 'Unidade Reciclagem Leste', 'Rodovia BR-040, km 20');

-- Inserir Transportadores
INSERT INTO TRANSPORTADOR VALUES (SEQ_TRANSPORTADOR.NEXTVAL, 'EcoTrans Ltda', '12345678000101', 'LIC-1234');
INSERT INTO TRANSPORTADOR VALUES (SEQ_TRANSPORTADOR.NEXTVAL, 'VerdeLog', '98765432000199', 'LIC-9876');
INSERT INTO TRANSPORTADOR VALUES (SEQ_TRANSPORTADOR.NEXTVAL, 'Recarte Transportes', '11122333000100', NULL);
INSERT INTO TRANSPORTADOR VALUES (SEQ_TRANSPORTADOR.NEXTVAL, 'SustentaMov', '44455566000122', 'LIC-2222');
INSERT INTO TRANSPORTADOR VALUES (SEQ_TRANSPORTADOR.NEXTVAL, 'TransEco', '77788899000111', 'LIC-3333');

-- Inserir Resíduos
INSERT INTO RESIDUO VALUES (SEQ_RESIDUO.NEXTVAL, 'Plástico', 150.00, SYSDATE - 10, 1);
INSERT INTO RESIDUO VALUES (SEQ_RESIDUO.NEXTVAL, 'Metal', 200.00, SYSDATE - 9, 2);
INSERT INTO RESIDUO VALUES (SEQ_RESIDUO.NEXTVAL, 'Vidro', 120.00, SYSDATE - 8, 3);
INSERT INTO RESIDUO VALUES (SEQ_RESIDUO.NEXTVAL, 'Papel', 300.00, SYSDATE - 7, 4);
INSERT INTO RESIDUO VALUES (SEQ_RESIDUO.NEXTVAL, 'Orgânico', 500.00, SYSDATE - 5, 5);

-- Inserir Coletas
INSERT INTO COLETA VALUES (SEQ_COLETA.NEXTVAL, SYSDATE - 6, 'PENDENTE', 1, 1);
INSERT INTO COLETA VALUES (SEQ_COLETA.NEXTVAL, SYSDATE - 5, 'PENDENTE', 2, 2);
INSERT INTO COLETA VALUES (SEQ_COLETA.NEXTVAL, SYSDATE - 12, 'PENDENTE', 3, 4);
INSERT INTO COLETA VALUES (SEQ_COLETA.NEXTVAL, SYSDATE - 2, 'EM_TRANSPORTE', 4, 5);
INSERT INTO COLETA VALUES (SEQ_COLETA.NEXTVAL, SYSDATE - 1, 'FINALIZADA', 5, 1);

-- Inserir Destino Final
INSERT INTO DESTINO_FINAL VALUES (SEQ_DESTINO.NEXTVAL, 'Reciclagem', 'Centro Municipal', SYSDATE - 1, 5);

-- Inserir usuário admin padrão (senha: admin123)
INSERT INTO USUARIO VALUES (
    SEQ_USUARIO.NEXTVAL,
    'admin',
    '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy',
    'admin@gestao-residuos.com',
    'Administrador do Sistema',
    'ADMIN',
    1
);

-- Inserir usuário operador padrão (senha: operador123)
INSERT INTO USUARIO VALUES (
    SEQ_USUARIO.NEXTVAL,
    'operador',
    '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.',
    'operador@gestao-residuos.com',
    'Operador de Coletas',
    'OPERADOR',
    1
);

COMMIT;